#!/usr/bin/env node

// Generates public/sitemap.xml from the route table.
//
// The sitemap used to be maintained by hand, which is why all 27 product pages
// were missing from it while /cart — a page nobody should ever land on from a
// search result — was listed. Generating it means the sitemap cannot disagree
// with the site: a new product is in it the moment it is in the catalog, and a
// noindex page can never appear in it at all.

import { writeFileSync, readFileSync } from "node:fs";
import { sitemapRoutes, canonicalUrl, todayISO } from "../src/data/routes.js";

const OUT = "public/sitemap.xml";

const escapeXml = (value) => String(value)
  .replace(/&/g, "&amp;")
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")
  .replace(/"/g, "&quot;")
  .replace(/'/g, "&apos;");

const today = todayISO();
const routes = sitemapRoutes(today);
const absoluteImage = (image) => image.startsWith("http") ? image : canonicalUrl(image);

const body = routes.map(route => {
  const parts = [
    `    <loc>${escapeXml(canonicalUrl(route.path))}</loc>`,
    `    <lastmod>${escapeXml(route.lastmod || today)}</lastmod>`,
  ];
  if (route.changefreq) parts.push(`    <changefreq>${route.changefreq}</changefreq>`);
  if (route.priority) parts.push(`    <priority>${route.priority}</priority>`);
  if (route.image) {
    parts.push(
      "    <image:image>",
      `      <image:loc>${escapeXml(absoluteImage(route.image))}</image:loc>`,
      "    </image:image>",
    );
  }
  return `  <url>\n${parts.join("\n")}\n  </url>`;
}).join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
${body}
</urlset>
`;

let previous = "";
try { previous = readFileSync(OUT, "utf8"); } catch { /* first run */ }
if (previous !== xml) writeFileSync(OUT, xml);

console.log(`generate-sitemap: ${routes.length} indexable URLs${previous === xml ? " (unchanged)" : ""}`);
